### PR TITLE
Javascript Library Project

### PR DESCRIPTION
**Pull request by jubaan**
The Library project includes functionality as:

Adding/Removing Books.
Changing the Read status of the book.
Modal form.
Onclick listeners.

### CODE REVIEW

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello! Great work on your project! It looks and work great. However the architecture for the project is a bit different than expected and some small adjustments need to be done.

# Changes required 🔴 

- [ ] Please remember to use a `render()` function (The project is fine but the `render()` function is a naming convention required on this project) as you can see here: img

- [x] Please remove your `package-lock.json` from your .gitignore file .lock files should be in the repository to avoid problems with future versions of the dependencies. It also helps to keep the same versions in different installations of the app (production, development, etc...) 

- [ ] On your `generateBookHTML` you should use object destructuring to get the object values. `Object.values` does not destructure the object instead, it returns and array. Whats happening on your code is that you are converting an object into an array (basically you end with the same thing without the [key]) if you use standard ES6 syntax you can save yourself a loop and a lot f code. (The loop is not necessary here, remember loops are slower than simple destructuring).

Here is an example of destructuring in action: 
```JS
const hero = {
  name: 'Batman',
  realName: 'Bruce Wayne'
};

const { name, realName } = hero;
name;     // => 'Batman',
realName; // => 'Bruce Wayne' 
 ```

img2


After making the requested changes please resubmit your project for another review.

Cheers 🥇 

Code review by Mario Enrique Delgado Naranjo

**Comment by kitpao** [comment]
Hello @MarioDena  thank you for your feedback 😄 

1) About the first point, maybe that screenshot is old because we didn't see it in Odin Project: 
image

2) We now implemented destructuring, but we don't know how to skip the loop because we are adding `<tr>` inside and also checking for some values inside, we would appreciate if you could guide us in this issue

**Comment by lekegitrepo** [comment]
> Hello! Great work on your project! It looks and work great. However the architecture for the project is a bit different than expected and some small adjustments need to be done.
> 
> # Changes required 
> * [ ]  Please remember to use a `render()` function (The project is fine but the `render()` function is a naming convention required on this project) as you can see here: img
> * [x]  Please remove your `package-lock.json` from your .gitignore file .lock files should be in the repository to avoid problems with future versions of the dependencies. It also helps to keep the same versions in different installations of the app (production, development, etc...)
> * [ ]  On your `generateBookHTML` you should use object destructuring to get the object values. `Object.values` does not destructure the object instead, it returns and array. Whats happening on your code is that you are converting an object into an array (basically you end with the same thing without the [key]) if you use standard ES6 syntax you can save yourself a loop and a lot f code. (The loop is not necessary here, remember loops are slower than simple destructuring).
> 
> Here is an example of destructuring in action:
> 
> ```js
> const hero = {
>   name: 'Batman',
>   realName: 'Bruce Wayne'
> };
> 
> const { name, realName } = hero;
> name;     // => 'Batman',
> realName; // => 'Bruce Wayne' 
> ```
> 
> img2
> 
> After making the requested changes please resubmit your project for another review.
> 
> Cheers 
> 
> Code review by Mario Enrique Delgado Naranjo

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Request changes :recycle:
### This is a nice project :star: you have done a good job :+1: However, as much as I would like to approve this project one of the required changes mentioned by the previous reviewer is not implemented :point_down:

- **_"Please remember to use a `render()` function (The project is fine but the `render()` function is a naming convention required on this project) as you can see here"_**: img

#### _Reviewed by Temitayo Adeleke_

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @kitpao and @jubaan :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by MarioDena** [comment]
> 
> 
> Hello @MarioDena thank you for your feedback 😄
> 
>     1. About the first point, maybe that screenshot is old because we didn't see it in Odin Project:
>        image
> 
>     2. We now implemented destructuring, but we don't know how to skip the loop because we are adding `<tr>` inside and also checking for some values inside, we would appreciate if you could guide us in this issue

Hello @kitpao of course. What I would do is have a component for my book that just displays everything in place. The code could be something like this: (Please keep in mind this is pseudo code)

```JS

const row = document.createElement('tr');
  const {
    author, title, pages, read,
  } = book;

// Components drawing everything 
titleH = document.createElement("your pick")
authorH = ...
pagesH = ...
readH  = ...

titleH.textContent = title;
authorH.textContent = author;
pagesH.textContent = pages;
readH.textContent = read;

row.appendChild(title)
// etc...


  iconize(readH, book);
  createDeleteBtn(row);

  return row;

```


The advantage of this is that, you could even create an HTML fragment somewhere else and just send in the data (simulating react) But it is also super simple to add a new element, having all elements with different styles, move them etc. 

But a more real scenario is imagine you have 1000's of books with 1000's of data to display on a database or API. You would need to loop over each of them. (This already happens in your "render")

```JS
function render() {
  const containerTable = document.querySelector('.library-body');

  myLibrary.forEach(book => {
    const eachBook = generateBookHTML(book);
    containerTable.appendChild(eachBook);
  });
}
```

And after doing 1000's of loops you then loop again over every property. Double looping like that generates way too much complexity and eventually your code would crash. You can read about Big O notation complexity on nested loops here: http://pages.cs.wisc.edu/~vernon/cs367/notes/3.COMPLEXITY.html


So I would have a predefined easy to edit HTML element created to send out "book" object over there. (On react you don't even have to create elements you just take properties and write JSX html over each property so I recommend you to simulate that)

Of course your code is fine as long as you use  destructuring (You already added that) it will get approved.

**Comment by kitpao** [comment]
> Hello @kitpao of course. What I would do is have a component for my book that just displays everything in place. The code could be something like this: (Please keep in mind this is pseudo code)
> ...


@MarioDena Thank you!!! I will try it :D

**Pull request merged**
